apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-config
  namespace: default
data:
  application.yml: |
    spring:
      application:
        name: auth-service
    eureka:
      client:
        service-url:
          defaultZone: http://eureka-server:8761/eureka/
    mongodb:
      uri: mongodb://mongo-auth:27017/authdb
