apiVersion: v1
kind: Service
metadata:
  name: board-service
spec:
  selector:
    app: board-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: board-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: board-service
  template:
    metadata:
      labels:
        app: board-service
    spec:
      containers:
      - name: board-service
        image: your-docker-repo/board-service:latest
        ports:
        - containerPort: 8081  # Board 서비스가 사용하는 포트
        env:
        - name: SPRING_DATA_MONGODB_URI
          valueFrom:
            configMapKeyRef:
              name: board-config
              key: mongodb.uri
        volumeMounts:
        - name: config-volume
          mountPath: /config/application.yml
          subPath: application.yml
      volumes:
      - name: config-volume
        configMap:
          name: board-config
