apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: your-docker-repo/user-service:latest
        ports:
        - containerPort: 8082  # User 서비스가 사용하는 포트
        env:
        - name: SPRING_DATA_MONGODB_URI
          valueFrom:
            configMapKeyRef:
              name: user-config
              key: mongodb.uri
        volumeMounts:
        - name: config-volume
          mountPath: /config/application.yml
          subPath: application.yml
      volumes:
      - name: config-volume
        configMap:
          name: user-config

