apiVersion: v1
kind: Secret
metadata:
  name: mongo-secrets
type: Opaque
data:
  root-username: aGVveW0xMTE=  # heoym111
  root-password: a2luZ2hlbzEyMw==  # kingheo123
  user-username: aGVveW0xMTE=  # heoym111
  user-password: a2luZ2hlbzEyMw==  # kingheo123
  MONGO_INITDB_DATABASE: aGVveW0xMTE=  #heoym111