server:
  port: 9001

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8055
          predicates:
            - Path=/user/**
#          filters:
#            - StripPrefix=1
        - id: board-service
          uri: http://localhost:8021
          predicates:
            - Path=/board/**
#          filters:
#            - StripPrefix=1
#      default-filters:
#        - name : GlobalAuthFilter

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
