server:
  port: 9001

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
#        - id: member-service
#          uri: lb://member-service
#          predicates:
#            - Path=/api/members/**
        - id: board-service
          uri: http://localhost:8021
          predicates:
            - Path=/board/**
#      default-filters:
#        - name : GlobalAuthFilter

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
