server:
  port: 8055

spring:
  application:
    name: user-service

  data:
    mongodb:
      uri: mongodb://user:1234@34.68.101.250:27017/user # MongoDB 연결 문자열

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    disable-delta: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
